source 'https://rubygems.org'

gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'mysql2', '>= 0.3.18', '< 0.5'
gem 'puma', '~> 3.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'jquery-rails'
gem 'turbolinks', '~> 5'
gem 'bootstrap-sass'
gem 'font-awesome-rails'
gem 'jbuilder', '~> 2.5'
gem 'haml'
gem 'bootstrap_form'
gem 'active_link_to'
gem 'nifty-utils'
gem 'will_paginate'
gem 'carrierwave'
gem 'fog'
gem 'mini_magick'
gem 'fullcalendar-rails'
gem 'momentjs-rails'

group :development do
  gem 'dotenv-rails'
  gem 'annotate'
  gem 'powder'
  gem 'app_reset'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'letter_opener'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
