# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac39bc7493290d29576ed50fa8caf842f483b51abd6cecee5e641d0787670654e14adc21bd1ea83fce0b4eb62c8a91d4b4b38ca602a25df6a2e89ce72b0c12b8

test:
  secret_key_base: 463799490e6ee8a869d2defd49adb63e54ed081479f8d0bd06e76e3fc37e5fc04d61728b818e66a21662fb57892c7919dc47b1fdd55fb4189bb92f94cd6cedea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
